version: 2.1

jobs:
  hello-world:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Greeting
          command: |
            echo 'Hello World!'
            echo 'Is this thing on?'

workflows:
  build:
    jobs:
      - hello-world
